# Generated by Django 3.2.14 on 2023-04-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_auto_20230415_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description_1',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='video',
            name='name_1',
        ),
        migrations.RemoveField(
            model_name='video',
            name='name_2',
        ),
        migrations.RemoveField(
            model_name='video',
            name='name_3',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_1',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_2',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_3',
        ),
    ]
