# Generated by Django 3.2.14 on 2023-04-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0006_auto_20230415_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
    ]
