# Generated by Django 3.2.14 on 2023-03-31 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='bio_image')),
                ('bio', models.TextField()),
            ],
            options={
                'verbose_name': 'Биография',
                'verbose_name_plural': 'Биография',
            },
        ),
        migrations.CreateModel(
            name='LastTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date', models.DateField(default=datetime.date(2023, 3, 31))),
                ('track', models.FileField(upload_to='main_tracks')),
            ],
            options={
                'verbose_name': 'Последние трэки',
                'verbose_name_plural': 'Последние трэки',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='video')),
            ],
            options={
                'verbose_name': 'Видео главной страницы',
                'verbose_name_plural': 'Видео главной страницы',
            },
        ),
    ]
