# Generated by Django 3.2.14 on 2023-03-31 12:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasttrack',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 31, 12, 52, 23, 501405, tzinfo=utc)),
        ),
    ]
