# Generated by Django 3.2.14 on 2023-03-31 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_lasttrack_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasttrack',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
