# Generated by Django 3.2.14 on 2023-03-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_video_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='galery_image')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='galery_image')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='galery_image')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='galery_image')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='galery_image')),
            ],
            options={
                'verbose_name': 'Галерея фотографий',
                'verbose_name_plural': 'Галерея фотографий',
            },
        ),
    ]
