# Generated by Django 3.2.14 on 2023-04-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_video_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='description2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='description3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='description4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='name1',
            field=models.CharField(default='now', max_length=256),
        ),
        migrations.AddField(
            model_name='video',
            name='name2',
            field=models.CharField(default='now', max_length=256),
        ),
        migrations.AddField(
            model_name='video',
            name='name3',
            field=models.CharField(default='now', max_length=256),
        ),
        migrations.AddField(
            model_name='video',
            name='name4',
            field=models.CharField(default='now', max_length=256),
        ),
        migrations.AddField(
            model_name='video',
            name='video1',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
        migrations.AddField(
            model_name='video',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
        migrations.AddField(
            model_name='video',
            name='video3',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
        migrations.AddField(
            model_name='video',
            name='video4',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
