# Generated by Django 3.2.14 on 2023-04-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230414_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
