# Generated by Django 3.2.14 on 2023-04-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео главной страницы', 'verbose_name_plural': 'Видео главной страницы'},
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
